apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rizkynova/learn-nov.git
    targetRevision: main
    path: apps
  destination:
    server: https://100.106.247.9:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
